import "@/styles/globals.css";
import { Providers } from "@/redux/provider";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import AOSInit from "@/utils/AOSInit";
import ScrollToTop from "@/utils/scrollToTop";
require("dotenv").config();

export const metadata = {
  title: "جعبه لغات ",
  description: "Generated by create next app",
  icons: "/img/images.webp"
};

const inter = Inter({ subsets: ["latin"] });

export default function App({ Component, pageProps }) {
  
  return (
    <Providers>
            {/* <AOSInit /> */}
            <Component {...pageProps} />
          {/* <div className='fixed bottom-4 left-4  '>
            <ScrollToTop />
          </div> */}
       </Providers>
  
  );
}
